# Generated by Django 5.0.2 on 2024-04-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image_url',
            field=models.URLField(default='https://i.ytimg.com/vi/eFQlfZFMqdk/default.jpg'),
            preserve_default=False,
        ),
    ]
