# Generated by Django 5.0.2 on 2024-04-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_app', '0002_video_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='plot',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
