# Generated by Django 5.0.2 on 2024-04-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_app', '0004_alter_video_plot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='plot',
            field=models.TextField(),
        ),
    ]
