# Generated by Django 5.0.4 on 2024-04-13 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('channel_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=100)),
                ('picture_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('image_url', models.URLField()),
                ('plot', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('time_published', models.DateTimeField()),
                ('num_comments', models.IntegerField()),
                ('positive', models.IntegerField()),
                ('negative', models.IntegerField()),
                ('rating', models.FloatField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.creator')),
            ],
        ),
    ]
